Remove NaN values in spatial_rate_map
CINPLA/exana-legacy pull request #21
Opened 2018-05-21 15:42 UTC by dragly

Otherwise, numpy.digitize will return indices that are outside the bins.

2018-05-21 15:43 UTC, dragly commented
This is perhaps something we want to add in a general function that can be used in other places.

@simetenn You've had some experience with removing NaNs in UncertainPy. Does this look good to you?

2018-05-22 16:11 UTC, simetenn requested changes

2018-05-22 16:11 UTC, simetenn commented on exana/tracking/fields.py
> +    if np.isnan(x).any() or np.isnan(y).any() or np.isnan(z).any():
I assume that np.isnan(z) -> np.isnan(t).

2018-05-22 16:11 UTC, simetenn commented on exana/tracking/fields.py
> +        nan_indices = np.isnan(x) & np.isnan(y) & np.isnan(t)
This should work as long as x, y, and t are numpy arrays of type float/int and not None, numpy arrays of type object, or float/ints (i think?).

2018-05-24 14:53 UTC, dragly commented on exana/tracking/fields.py
> +    if np.isnan(x).any() or np.isnan(y).any() or np.isnan(z).any():
that's correct :)

2018-05-24 14:54 UTC, dragly commented on exana/tracking/fields.py
> +        nan_indices = np.isnan(x) & np.isnan(y) & np.isnan(t)
x, y and t should be quantities arrays of type float

2019-08-15 12:52 UTC, closed without merging